package main

import "wb-l1-tasks/tasks"

func main() {
	// tasks.Task1()
	// tasks.Task2()
	// tasks.Task3()
	// tasks.Task4()
	// tasks.Task5()
	// tasks.Task6()
	// tasks.Task7()
	// tasks.Task8()
	// tasks.Task9()
	// tasks.Task10()
	// tasks.Task11()
	// tasks.Task12()
	// tasks.Task13()
	// tasks.Task14()
	// tasks.Task15()
	// tasks.Task16()
	// tasks.Task17()
	// tasks.Task18()
	// tasks.Task19()
	// tasks.Task20()
	// tasks.Task21()
	// tasks.Task22()
	// tasks.Task23()
	// tasks.Task24()
	// tasks.Task25()
	// tasks.Task26()
	// tasks.Task27()
	// tasks.Task28()
	// tasks.Task29()
	// tasks.Task30()
	// tasks.Task31()
	// tasks.Task32()
	// tasks.Task33()
	// tasks.Task34()
	// tasks.Task35()
	// tasks.Task36()
	// tasks.Task37()
	// tasks.Task38()
	// tasks.Task39()
	// tasks.Task40()
	tasks.Task41()
}
